services:
  # 1. Database Layer: Hardened Bitnami MongoDB
  db:
    image: bitnami/mongodb@sha256:45b7d1b7470d061ddc089b743972916659e0e8a5c0df64db79466b8d5d0c2069
    container_name: mongodb
    restart: always
    environment:
      - MONGODB_DATABASE=todo-db
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_USERNAME=ebad
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval \"db.adminCommand('ping')\" || mongo --eval \"db.adminCommand('ping')\""]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongodb_data:/bitnami/mongodb
    networks:
      - backend-nw

  # 2. Backend Layer: Node.js (Distroless)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      - MONGODB_URI=mongodb://ebad:${MONGODB_PASSWORD}@db:27017/todo-db?authSource=todo-db
      - PORT=5000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend-nw
      - backend-nw

  # 3. Frontend Layer: Nginx (Reverse Proxy)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    depends_on:
      - backend
    networks:
      - frontend-nw

# Network Isolation
networks:
  frontend-nw:
  backend-nw:

# Persistence Storage
volumes:
  mongodb_data:
    driver: local