name: Backend CI

on:
  push:
    branches: [ master ]
    paths:
      - 'server/**'
      - '.github/workflows/backend-ci.yml'

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  BACKEND_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/todo-backend:${{ github.sha }}

jobs:
  security-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trivy FS Scan (Source Code)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          scan-ref: './server'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and Scan Backend
      - name: Build Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          load: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
            ${{ env.BACKEND_IMAGE }}:latest

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '${{ env.BACKEND_IMAGE }}:${{ github.sha }}'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '1'

      - name: Push Images to Docker Hub
        if: github.event_name == 'push'
        run: |
          docker push ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          docker push ${{ env.BACKEND_IMAGE }}:latest