name: "Infrastructure CD"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Type "destroy" to delete infrastructure'
        required: false
        default: 'apply'

permissions:
  contents: read
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './terraform/environments/${{ vars.TERRAFORM_WORKSPACE }}'
    env:
      TF_VAR_mongodb_root_password: ${{ secrets.MONGODB_ROOT_PASSWORD }}
      TF_VAR_mongodb_password: ${{ secrets.MONGODB_PASSWORD }}
      TF_VAR_docker_username: ${{ vars.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init & Workspace
        run: |
          terraform init
          terraform workspace select ${{ vars.TERRAFORM_WORKSPACE }} 2>/dev/null || terraform workspace new ${{ vars.TERRAFORM_WORKSPACE }}

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: |
          if [[ "${{ github.event.inputs.action }}" == "destroy" ]]; then
            echo "DESTROYING INFRASTRUCTURE..."
            terraform destroy -auto-approve
          else
            echo "APPLYING CHANGES..."
            terraform apply -auto-approve
          fi